/*
 * Sample Application Flow OAuth2 Project
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApplicationFlowOAuth2Project);
  }
}(this, function(expect, SampleApplicationFlowOAuth2Project) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApplicationFlowOAuth2Project.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('exampleGet', function() {
        it('should call exampleGet successfully', function(done) {
          // TODO: uncomment exampleGet call
          /*

          instance.exampleGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pingGet', function() {
        it('should call pingGet successfully', function(done) {
          // TODO: uncomment pingGet call
          /*

          instance.pingGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
